dist: xenial
language: generic
addons:
  apt:
    packages:
    - unzip
install:
- python -m pip install --user pygments restructuredtext-lint
before_script:
- curl --version
script:
- shellcheck opensubtitles-dl
- restructuredtext-lint --encoding=UTF-8 README
- OPENSUBSTITLES_DL_ONLINE_TESTS=1 prove -v

# vim:ts=2 sts=2 sw=2 et
